import {perguntas} from "./database.js"

//ALGORITMO PARA RETORNAR PERGUNTA, AS ALTERNATIVAS E A RESPOSTA CORRETA DO OBEJETO 'PERGUNTAS' DE ACORDO COM UM INDICE GERADO ALEATORIAMENTE

// ALGORITMO PARA ATUALIZAR CAMPOS DO HTML

// ALGORITMO DE PONTUAÇÃO

// ALGORITMO DE TEMPO

